version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  target-branch: "develop"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  reviewers:
  - duttonw
  - qld-gov-au/qld-online-dev-team
  ignore:
  - dependency-name: nth-check
  - dependency-name: cssnano
  - dependency-name: jquery
  - dependency-name: bootstrap
  - dependency-name: del
  - dependency-name: terser-webpack-plugin
  - dependency-name: eslint-config-semistandard
  - dependency-name: eslint-config-standard
